[format]
line-width = 80
indent-width = 2
indent-style = "space"
line-ending = "auto"
persistent-line-breaks = true
exclude = [".Renviron", ".yaml", ".toml", ".json", ".md"]
default-exclude = true
skip = ["tribble"]
